---
- name: Config Backup
  hosts: all
  gather_facts: false
  tasks:
  - name: Config Backup
    cisco.ios.ios_config:
      backup: yes
    register: config_Backup 
    
  - name: Print Command Output
    ansible.builtin.debug:
        msg: "{{ config_Backup  }}"

# config backup without any dedicated or specific folder and specific filename.it will create one backup folder within same directory it will add config files in that directory.