---
- name: playbook demo
  hosts: all
  gather_facts: true
  tasks:
    - name: Take ios config Backup 
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: /home/ganapathi/Documents/Ansible-Network-Automation/Ansible/playbooks/cisco.ios.ios_config module/backup/ {{ inventory_hostname }}/
          filename: "{{ inventory_hostname }}_{{ ansible_ssh_host }}.txt"
      register: config_Backup 
    
    - name: Print Command Output
      ansible.builtin.debug:
        msg: "{{ config_Backup  }}"

#we can download config backup  with specific folder/directory and specific file name.